# Generated by Django 5.0 on 2026-06-14 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_progressrecord_created_at'),
        ('syllabus', '0002_exam_description_exam_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('concepts_attempted', models.JSONField(blank=True, default=list)),
                ('concepts_completed', models.JSONField(blank=True, default=list)),
                ('questions_solved', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('revision_count', models.IntegerField(default=0)),
                ('energy_score', models.IntegerField(default=50)),
                ('focus_score', models.IntegerField(default=50)),
                ('mood', models.CharField(default='neutral', max_length=50)),
                ('knowledge_gain', models.JSONField(blank=True, default=dict)),
                ('accuracy', models.FloatField(default=0.0)),
                ('daily_growth_percentage', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('target_growth', models.FloatField(default=0.83)),
                ('completed_growth', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('available_hours_per_day', models.FloatField(default=2.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
