# Generated by Django on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_dailydiaryentry_dailytarget_usergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytarget',
            name='completed_correct_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='study_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='target_correct_questions',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='dailytarget',
            name='target_growth',
            field=models.FloatField(default=100.0),
        ),
    ]
