# Generated by Django on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_daily_target_dual_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptprogress',
            name='chapter_understanding',
        ),
        migrations.RemoveField(
            model_name='conceptprogress',
            name='exam_readiness',
        ),
        migrations.AddField(
            model_name='conceptprogress',
            name='readiness',
            field=models.FloatField(default=0.0),
        ),
    ]
