# Generated by Django 5.2.16 on 2026-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_unified_concept_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydiaryentry',
            name='readiness_delta',
            field=models.FloatField(default=0.0),
        ),
    ]
