# Generated by Django 5.2.16 on 2026-09-21 06:30

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_dailydiaryentry_readiness_delta'),
        ('quiz', '0003_rename_quiz_questi_concept_6c8d76_idx_quiz_questi_concept_5461cf_idx'),
        ('syllabus', '0004_exam_code_exam_is_active_exam_parent_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conceptprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailydiaryentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dailytarget',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progressrecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subtopicprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailydiaryentry',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='required_readiness_per_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailydiaryentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailydiaryentry',
            name='questions_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydiaryentry',
            name='questions_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydiaryentry',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailytarget',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='main_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='main_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='sub_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='sub_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='conceptprogress',
            constraint=models.UniqueConstraint(fields=('user', 'concept'), name='unique_user_concept_progress'),
        ),
        migrations.AddConstraint(
            model_name='dailydiaryentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_diary'),
        ),
        migrations.AddConstraint(
            model_name='dailytarget',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_target'),
        ),
        migrations.AddConstraint(
            model_name='progressrecord',
            constraint=models.UniqueConstraint(fields=('user', 'concept', 'quiz_session'), name='unique_user_concept_session_record'),
        ),
        migrations.AddConstraint(
            model_name='subtopicprogress',
            constraint=models.UniqueConstraint(fields=('user', 'subtopic'), name='unique_user_subtopic_progress'),
        ),
        migrations.AddConstraint(
            model_name='usergoal',
            constraint=models.UniqueConstraint(fields=('user', 'exam'), name='unique_user_exam_goal'),
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='daily_growth_percentage',
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='energy_score',
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='focus_score',
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='knowledge_gain',
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='dailydiaryentry',
            name='revision_count',
        ),
        migrations.RemoveField(
            model_name='dailytarget',
            name='completed_correct_questions',
        ),
        migrations.RemoveField(
            model_name='dailytarget',
            name='completed_growth',
        ),
        migrations.RemoveField(
            model_name='dailytarget',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='dailytarget',
            name='study_checked_in',
        ),
        migrations.RemoveField(
            model_name='dailytarget',
            name='target_correct_questions',
        ),
        migrations.RemoveField(
            model_name='dailytarget',
            name='target_growth',
        ),
        migrations.RemoveField(
            model_name='subtopicprogress',
            name='raw_efficiency',
        ),
    ]
