# Generated by Django on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mode',
            field=models.CharField(choices=[('LLM', 'LLM Question Generation'), ('FULL_EXAM', 'Full Exam Simulation'), ('PYQS', 'Past Year Questions')], default='PYQS', max_length=20),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='mode',
            field=models.CharField(choices=[('LLM', 'LLM Question Generation'), ('FULL_EXAM', 'Full Exam Simulation'), ('PYQS', 'Past Year Questions')], default='PYQS', max_length=20),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['concept', 'mode'], name='quiz_questi_concept_6c8d76_idx'),
        ),
    ]
