# Generated by Django 5.2.16 on 2026-09-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_examsimulationsession_simulationquestionresponse_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='quiz_questi_concept_5461cf_idx',
            old_name='quiz_questi_concept_6c8d76_idx',
        ),
    ]
