# Generated by Django 4.0.3 on 2026-07-29 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalystMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('FIRST_LOGIN', 'First Login'), ('RETURN_AFTER_BREAK', 'Return After Break'), ('GOAL_SET', 'Goal Just Set'), ('QUIZ_FAILED_REPEAT', 'Repeated Quiz Failure'), ('QUIZ_PERFECT', 'Perfect Quiz Score'), ('CONCEPT_MASTERED', 'Concept Mastered'), ('STREAK_MILESTONE', 'Streak Milestone'), ('IDENTITY_UNLOCKED', 'Identity Title Unlocked'), ('LOW_ENERGY', 'Low Energy Reported'), ('MOMENTUM_FALLING', 'Momentum Falling'), ('DAILY_TARGET_HIT', 'Daily Target Hit'), ('THRIVING', 'User Thriving'), ('AT_RISK', 'User At Risk'), ('GENERIC_INSIGHT', 'Generic Insight')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('cta_action', models.CharField(blank=True, max_length=100)),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='UserStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMindProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.5)),
                ('momentum_score', models.FloatField(default=0.5)),
                ('momentum_direction', models.CharField(choices=[('rising', 'Rising'), ('steady', 'Steady'), ('falling', 'Falling'), ('dormant', 'Dormant')], default='steady', max_length=10)),
                ('current_state', models.CharField(choices=[('thriving', 'Thriving'), ('on_track', 'On Track'), ('needs_encouragement', 'Needs Encouragement'), ('needs_challenge', 'Needs Challenge'), ('at_risk', 'At Risk')], default='on_track', max_length=25)),
                ('fear_areas', models.JSONField(blank=True, default=list)),
                ('strength_areas', models.JSONField(blank=True, default=list)),
                ('avoidance_pattern', models.JSONField(blank=True, default=list)),
                ('best_study_hour', models.IntegerField(blank=True, null=True)),
                ('avg_session_length', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mind_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONCEPT_STARTED', 'Concept Started'), ('CONCEPT_COMPLETED', 'Concept Completed'), ('SESSION_ABANDONED', 'Session Abandoned'), ('QUIZ_STARTED', 'Quiz Started'), ('QUIZ_PASSED', 'Quiz Passed'), ('QUIZ_FAILED', 'Quiz Failed'), ('QUIZ_FAILED_REPEAT', 'Quiz Failed Repeat'), ('RETURN_AFTER_BREAK', 'Return After Break'), ('GOAL_SET', 'Goal Set'), ('ENERGY_REPORTED', 'Energy Reported'), ('STREAK_MILESTONE', 'Streak Milestone'), ('CONCEPT_MASTERED', 'Concept Mastered'), ('IDENTITY_UNLOCKED', 'Identity Unlocked'), ('ONBOARDING_COMPLETED', 'Onboarding Completed')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userbehaviorevent',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='behavior_us_user_id_249388_idx'),
        ),
    ]
