# Generated by Django 4.0.3 on 2026-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalystmessage',
            name='tone',
            field=models.CharField(choices=[('mentor', 'Mentor — warm, patient, no pressure'), ('challenger', 'Challenger — direct, sharp, playful'), ('companion', 'Companion — curious, gentle, exploratory'), ('any', 'Any — tone-agnostic, works for all')], db_index=True, default='any', max_length=12),
        ),
        migrations.AlterField(
            model_name='catalystmessage',
            name='trigger',
            field=models.CharField(choices=[('FIRST_LOGIN', 'First Login'), ('RETURN_AFTER_BREAK', 'Return After Break'), ('GOAL_SET', 'Goal Just Set'), ('QUIZ_FAILED_REPEAT', 'Repeated Quiz Failure'), ('QUIZ_PERFECT', 'Perfect Quiz Score'), ('CONCEPT_MASTERED', 'Concept Mastered'), ('STREAK_MILESTONE', 'Streak Milestone'), ('IDENTITY_UNLOCKED', 'Identity Title Unlocked'), ('LOW_ENERGY', 'Low Energy Reported'), ('MOMENTUM_FALLING', 'Momentum Falling'), ('DAILY_TARGET_HIT', 'Daily Target Hit'), ('THRIVING', 'User Thriving'), ('AT_RISK', 'User At Risk'), ('GENERIC_INSIGHT', 'Generic Insight'), ('CURIOSITY_PROMPT', 'Curiosity — Ask before Notes'), ('DIRECT_CHALLENGE', 'Challenge — Skip to Test'), ('ENCOURAGEMENT', 'Encourage — Fear Area Support'), ('CELEBRATION', 'Celebrate — Milestone'), ('FOCUSED_EXPLAIN', 'Explain — Repeated Failure'), ('REFLECTION_PROMPT', 'Reflect — Long Session / Drift'), ('PREDICTION_NARRATIVE', 'Predict — Growth Story'), ('IDENTITY_ARRIVAL', 'Identity — Mood Arrival Ritual')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='catalystmessage',
            index=models.Index(fields=['trigger', 'tone'], name='behavior_ca_trigger_31c8e3_idx'),
        ),
    ]
