# Generated by Django 5.2.16 on 2026-09-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_userprofile_selected_exam_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pcs_section',
            field=models.CharField(blank=True, default='BPSC', max_length=50),
        ),
    ]
