# Generated by Django 5.2.8 on 2026-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('jee', 'JEE Main'), ('neet', 'NEET'), ('placement', 'Placement Preparation')], default='jee', help_text='Determines which prompt module is used for AI generation', max_length=50),
        ),
    ]
