# Generated by Django 5.0 on 2026-09-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_exam_description_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('jee', 'JEE Main'), ('neet', 'NEET'), ('placement', 'Placement Preparation'), ('pcs', 'State PCS (BPSC, UPPCS, etc.)')], default='jee', help_text='Determines which prompt module is used for AI generation', max_length=50),
        ),
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('exam_source', models.CharField(max_length=255)),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('source_book', models.CharField(blank=True, default='Ghatnachakra Indian History 2025', max_length=255)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('source_question_number', models.CharField(blank=True, max_length=100)),
                ('experiential_summary', models.JSONField(blank=True, default=dict, help_text='Structured dict with keys: trend, pattern, trap, memory_hook')),
                ('extraction_confidence', models.FloatField(blank=True, default=1.0, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='syllabus.concept')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
