# Generated by Django 5.2.16 on 2026-09-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_alter_exam_exam_type_pyq'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='code',
            field=models.CharField(blank=True, help_text='Short identifier/code like BPSC, UPPSC, WBPSC, JEE_MAIN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='parent_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='syllabus.exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('jee', 'JEE Main'), ('neet', 'NEET'), ('placement', 'Placement Preparation'), ('pcs', 'State PCS')], default='jee', help_text='Determines which prompt module is used for AI generation', max_length=50),
        ),
    ]
