# Generated by Django 4.0.3 on 2026-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_reputationpoint_mentorshipticket_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='domain_tag',
            field=models.CharField(blank=True, db_index=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='grade_level',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='relevance_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('doc', 'Document'), ('mixed', 'Mixed'), ('progress', 'Progress Update'), ('milestone', 'Learning Milestone'), ('project', 'Project Showcase'), ('help', 'Help Request'), ('discovery', 'Discovery'), ('opportunity', 'Opportunity'), ('discussion', 'Discussion'), ('story', 'Student Story'), ('experiment', 'Experiment'), ('failure', 'Failure & Lesson'), ('idea', 'Idea')], db_index=True, default='text', max_length=20),
        ),
    ]
