# Generated by Django 5.2.16 on 2026-09-19 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_domain_tag_post_grade_level_and_more'),
        ('syllabus', '0004_exam_code_exam_is_active_exam_parent_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('learning', 'Learning Insight'), ('strategy', 'Quiz Strategy'), ('general', 'General Reflection'), ('project', 'Project Showcase'), ('question', 'Question / Help'), ('discovery', 'Discovery'), ('opportunity', 'Opportunity')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('concept', 'Concept Page'), ('quiz', 'Quiz Result'), ('world', 'World Page')], db_index=True, default='world', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(db_index=True, default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source', 'created_at'], name='social_post_source_00f7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', 'created_at'], name='social_post_content_116017_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['domain_tag', 'created_at'], name='social_post_domain__82e993_idx'),
        ),
    ]
