# Generated by Django 5.2.16 on 2026-09-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_content_type_post_source_alter_post_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='domain_tag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
