

"""
Django settings for nimides project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-odia3xy&=g)5cx_e*-q5qq9$+cycyw!ji)+*^y2ws#gp@=g7yl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# "https://<social_pythonanywhere_username>.pythonanywhere.com/api/"

# Application definition
CORS_ALLOW_ALL_ORIGINS = True
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'social',
    "authapp.apps.AuthappConfig",
    "rest_framework_simplejwt.token_blacklist",
    'admin.apps.AdminAppConfig',
    'syllabus',
    'progress',
    'quiz',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nimides.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nimides.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import urllib.parse as urlparse
import socket

DATABASE_URL = os.environ.get('DATABASE_URL')
tmp_url = urlparse.urlparse(DATABASE_URL)
query_params = urlparse.parse_qs(tmp_url.query)

db_host = tmp_url.hostname
db_options = {key: val[0] for key, val in query_params.items()}

if db_host:
    try:
        socket.gethostbyname(db_host)
    except socket.gaierror:
        import struct
        def dns_resolve_8888(hostname):
            packet = struct.pack(">HHHHHH", 0x1234, 0x0100, 1, 0, 0, 0)
            for part in hostname.split('.'):
                part_bytes = part.encode('ascii')
                packet += struct.pack("B", len(part_bytes)) + part_bytes
            packet += struct.pack("B", 0)
            packet += struct.pack(">HH", 1, 1)
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                sock.settimeout(2.0)
                sock.sendto(packet, ("8.8.8.8", 53))
                data, _ = sock.recvfrom(512)
                num_answers = struct.unpack(">H", data[6:8])[0]
                offset = 12 + (len(packet) - 12)
                for _ in range(num_answers):
                    if (data[offset] & 0xc0) == 0xc0:
                        offset += 2
                    else:
                        while data[offset] != 0:
                            offset += 1 + data[offset]
                        offset += 1
                    type_, class_, ttl, rdlen = struct.unpack(">HHIH", data[offset:offset+10])
                    offset += 10
                    if type_ == 1 and rdlen == 4:
                        return socket.inet_ntoa(data[offset:offset+4])
                    offset += rdlen
            except Exception:
                pass
            return None

        resolved_ip = dns_resolve_8888(db_host)
        if resolved_ip:
            db_host = resolved_ip
            if "neon.tech" in (tmp_url.hostname or ""):
                endpoint_id = tmp_url.hostname.split('.')[0]
                db_options['options'] = f"endpoint={endpoint_id}"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmp_url.path[1:],
        'USER': tmp_url.username,
        'PASSWORD': tmp_url.password,
        'HOST': db_host,
        'PORT': tmp_url.port or '',
        'OPTIONS': db_options,
        'DISABLE_SERVER_SIDE_CURSORS': True,
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
REDIS_URL=os.environ.get("REDIS_URL")
# Caching Configuration
# USE_CACHING = os.environ.get('USE_CACHING', 'False').lower() in ('true', '1', 't')
USE_CACHING = True
if USE_CACHING:
    # On Render, use the internal REDIS_URL.
    # Locally, use REDIS_EXTERNAL_URL if set, otherwise fallback to REDIS_URL.
    if os.environ.get('RENDER'):
        REDIS_URL = os.environ.get('REDIS_URL')
    else:
        REDIS_URL = os.environ.get('REDIS_EXTERNAL_URL') or os.environ.get('REDIS_URL')
    
    # Validate Redis URL format
    is_valid_redis_url = False
    if REDIS_URL:
        for scheme in ("redis://", "rediss://", "unix://"):
            if REDIS_URL.startswith(scheme):
                is_valid_redis_url = True
                break
                
        if is_valid_redis_url:
            try:
                parsed_redis = urlparse.urlparse(REDIS_URL)
                redis_host = parsed_redis.hostname
                # If running locally and hostname is a bare Render internal name (no dots), bypass it
                if redis_host and "." not in redis_host and not os.environ.get('RENDER'):
                    is_valid_redis_url = False
            except Exception:
                is_valid_redis_url = False
                
    if is_valid_redis_url:
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': REDIS_URL,
            }
        }
    else:
        # Check if local Redis server is active on 6379
        local_redis_active = False
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(0.5)
            s.connect(("127.0.0.1", 6379))
            s.close()
            local_redis_active = True
        except Exception:
            pass
            
        if local_redis_active:
            CACHES = {
                'default': {
                    'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                    'LOCATION': 'redis://127.0.0.1:6379',
                }
            }
        else:
            # Fallback to local memory cache for local development/testing when REDIS_URL is not set or invalid
            CACHES = {
                'default': {
                    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                    'LOCATION': 'unique-snowflake',
                }
            }
else:
    # DummyCache acts as a pass-through (noop) cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

# Print current active database and cache settings on startup/reload
print(f"--> [DATABASE] ENGINE: {DATABASES['default']['ENGINE']} | HOST: {DATABASES['default']['HOST']}")
print(f"--> [CACHE] BACKEND: {CACHES['default']['BACKEND']} | LOCATION: {CACHES['default'].get('LOCATION', 'None')}")


# Stop-Process -Name "python" -Force
